version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_backend:
    build:
      context: .
      dockerfile: accounting_for_pets/Dockerfile
    volumes:
      - static_value:/app/accounting_for_pets/staticfiles/
      - media_value:/app/accounting_for_pets/media/
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - 8000

  nginx_proxy:
    image: nginx:alpine
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - django_backend

volumes:
  postgres_data:
  static_value:
  media_value:
